--- #YAML:1.0
name:               BSD-Process
version:            0.07
abstract:           Information about running processes on BSD platforms
author:
    - David Landgren
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:  0.25
    perl:             5.008001
    XSLoader:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
