--- #YAML:1.0
name:                BSD-Process
version:             0.04
abstract:            Information about running processes on BSD platforms
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    Class::Accessor:               0.25
    XSLoader:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - David Landgren
